source("./nanosim.R")

args <- commandArgs(trailingOnly = TRUE)

#wl = scan("~/data/BarcodeMatch/FT/FT_cells.txt",character(), quote = "")
#wl = scan("/D/Necessary/Upenn/Thesis/data/FT_gp5/FT_cells.txt",character(), quote = "")

#cells =  scan("/D/Necessary/Upenn/Thesis/projects/Single-cell-long-reads/data/preprocess/simulation/bench_cells.txt",character(), quote = "")
cells = scan("~/data/bench/simulation/bench_cells.txt",character(), quote = "")
exprs = c(5,10,25,50,80,120)
#transcripts = c("CTCTCGGCCTTAGCGCCATTTTTTTGGGTGAGTGTTTTTTGGTTCCTGCGTTGGGATTCCGTGTACAATCCATAGACATCTGACCTCGGCACTTAGCATCATCACAGCAAACTAACTGTAGCCTTTCTCTCTTTCCCTGTAGAAACCTCTGCGCCATGAGAGCCAAGTGGAGGAAGAAGCGAATGCGCAGGCTGAAGCGCAAAAGAAGAAAGATGAGGCAGAGGTCCAAGTAAACCGCTAGCTTGTTGCACCGTGGAGGCCACAGGAGCAGAAACATGGAATGCCAGACGCTGGGGATGCTGGTACAAGTTGTGGGACTGCATGCTACTGTCTAGAGCTTGTCTCAATGGATCTAGAACTTCATCGCCCTCTGATCGCCGATCACCTCTGAGACCCACCTTGCTCATAAACAAAATGCCCATGTTGGTCCTCTGCCCTGGACCTGTGACATTCTGGACTATTTCTGTGTTTATTTGTGGCCGAGTGTAACAACCATATAATAAATCACCTCTTCCGCTGTTTTAGCTGAAGAATTAAATCATCTTGTCTATTATGTTTTTTATGGTTCCATCGGGTGGGGGTTTTCTGTCATTAGAGTTTGCCCTGTCACTACCTGTGCTATGGAGGGTATCAAAGCTATAAAGGCAACAGCCCGGGTTACGTGGTGTGGTTTGCA",
#                "CCTGTAGAAACCTCTGCGCCATGAGAGCCAAGGCTGAAGCGCAAAAGAAGAAAGATGAGGCAGAGGTCCAAGTAAACCGCTAGCTTGTTGCACCGTGGAGGCCACAGGAGCAGAAACATGGAATGCCAGACGCTGGGGATGCTGGTACAAGTTGTGGGACTGCATGCTACTGTCTAGAGCTTGTCTCAATGGATCTAGAACTTCATCGCCCTCTGATCGCCGATCACCTCTGAGACCC")
#transname = c("RPL41-204","RPL41-205")
transcripts = c("GGAGCCATTACTGCAGGAAAAGGTCCCGGAGAGCTGAGCAGTCAAGATGCAGTGTGACTTCACCGAAGACCAGACCGCAGAGTTCAAGGAGGCCTTCCAGCTGTTTGACCGAACAGGTGATGGCAAGATCCTGTACAGCCAGTGTGGGGATGTGATGAGGGCCCTGGGCCAGAACCCTACCAACGCCGAGGTGCTCAAGGTCCTGGGGAACCCCAAGAGTGATGAGATGAATGTGAAGGTGCTGGACTTTGAGCACTTTCTGCCCATGCTGCAGACAGTGGCCAAGAACAAGGACCAGGGCACCTATGAGGATTATGTCGAAGGACTTCGGGTGTTTGACAAGGAAGGAAATGGCACCGTCATGGGTGCTGAAATCCGGCATGTTCTTGTCACACTGGGTGAGAAGATGACAGAGGAAGAAGTAGAGATGCTGGTGGCAGGGCATGAGGACAGCAATGGTTGTATCAACTATGAAGAGCTCGTCCGCATGGTGCTGAATGGCTGAGGACCTTCCCAGTCTCCCCAGAGTCCGTGCCTTTCCCTGTGTGAATTTTGTATCTAGCCTAAAGTTTCCCTAGGCTTTCTTGTCTCAGCAACTTTCCCATCTTGTCTCTCTTGGATGATGTTTGCCGTCAGCATTCACCAAATAAACTTGCTCTCTGGG",
                "GGAGCCATTACTGCAGGAAAAGGTCCCGGAGAGCTGAGCAGTCAAGATGCAGTGTGACTTCACCGAAGACCAGACCGCAGAGTTCAAGGAGGCCTTCCAGCTGTTTGACCGAACAGGTGATGGCAAGATCCTGTACAGCCAGTGTGGGGATGTGATGAGGGCCCTGGGCCAGAACCCTACCAACGCCGAGGTGCTCAAGGTCCTGGGGAACCCCAAGAGTGATGAGATGAATGTGAAGGTGCTGGACTTTGAGCACTTTCTGCCCATGCTGCAGACAGTGGCCAAGAACAAGGACCAGGGCACCTATGAGGATTATGTCGAAGGACTTCGGGTGTTTGACAAGGAAGGAAATGGCACCGTCATGGGTGCTGAAATCCGGCATGTTCTTGTCACACTGGGTGAGAAGATGACAGAGGAAGAAGTAGAGATGCTGGTGGCAGGGCATGAGGACAGCAATGGTTGTATCAACTATGAAGCGTTTGTGAGGCATATCCTGTCGGGGTGACGGGCCCATGGGGCGGAGCTCGTCCGCATGGTGCTGAATGGCTGAGGACCTTCCCAGTCTCCCCAGAGTCCGTGCCTTTCCCTGTGTGAATTTTGTATCTAGCCTAAAGTTTCCCTAGGCTTTCTTGTCTCAGCAACTTTCCCATCTTGTCTCTCTTGGATGATGTTTGCCGTCAGCATTCACCAAATAAACTTGCTCTCTGGGCCCTCGGTTCGGT")
transname = c("MYL6-201","MYL6-202")
pcr = as.numeric(args[1])

path = args[2]
prefix = args[3]
prefix = paste(path,prefix,sep = "")

toolkit = as.numeric(args[5])
data = lapply(seq(1,length(cells),6),function(i){
  sub_cells = cells[i:(i+5)]
  reads_simulator(barcodes = sub_cells,exprs = exprs,
                  transcripts = transcripts, transname = transname,
                  alpha = 10,beta = 10,
                  pcr = pcr,toolkit = toolkit)
})
data = do.call(rbind,data)
file = paste(c(prefix,".fastq"),collapse = ".")
cache = dataframe2fastq(data,file)
command = paste(c("gzip ", prefix,".fastq"),collapse = "")
system(command)


saveRDS(data,file = paste(path,args[4],sep = "/"))



